# Generated by Django 5.0.1 on 2024-02-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_trabajosrealizados_kg_pota_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajosrealizados',
            name='kg_Pota_final',
        ),
    ]
