# Generated by Django 5.0.1 on 2024-02-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_trabajosrealizados_kg_pota_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajosrealizados',
            name='kg_grupo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=200),
        ),
        migrations.AddField(
            model_name='trabajosrealizados',
            name='promedio_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
